create column table test1 (
	 keycode bigint primary key 
	,strv varchar(100) 
	,decv decimal(16,4) 
	,datv date 
	,datv2 date 
	,enmv integer 
	,nbv integer not null
	,nst1 varchar(10) default 'nst1' 
	,nst2 decimal(14,4)
	,nss1 varchar(10) 
	,tms timestamp 
	,tms2 timestamp 
	,tm time
	,clb clob
	,blb blob
);

create column table test2 (
	 code bigint not null primary key generated by default as IDENTITY 
	,text varchar(100) not null
);

create column table test3 (
	 code bigint not null primary key
	,text varchar(100) not null
);

create column table test_recur (
	 code bigint not null primary key generated by default as IDENTITY 
	,name varchar(100) not null
	,parent varchar(100)
);

create column table test_nopk (
	nmb integer,
	txt varchar(10)
);
