version: '2'

services: 
  server:
    image: holon/sqlite
    command: socat TCP-L:12345,fork,reuseaddr EXEC:'sqlite3',pty
    build: . 
    volumes: 
    - /tmp/sqlitedbs/test:/opt/sqlite/db
  proxy:
    image: holon/sqlite
    build: .
    command: socat TCP-L:12346,fork,reuseaddr TCP:sqliteserver:12345
    links: server:sqliteserver
    ports: 
    - 12346:12346