# holon/oracle

# hostname: localhost
# port: 49161
# sid: xe
# username: system
# password: oracle

FROM wnameless/oracle-xe-11g-r2

ADD init.sql /docker-entrypoint-initdb.d/

EXPOSE 49161
