CREATE USER HOLON_TEST
  IDENTIFIED BY HOLON_TEST 
  --DEFAULT TABLESPACE TS
  --TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT 
  ACCOUNT UNLOCK;
  -- 3 Roles for HOLON_TEST 
  GRANT CONNECT TO HOLON_TEST;
  GRANT DBA TO HOLON_TEST;
  GRANT RESOURCE TO HOLON_TEST;
  ALTER USER HOLON_TEST DEFAULT ROLE ALL;
  -- 3 System Privileges for HOLON_TEST 
  GRANT CREATE ANY TABLE TO HOLON_TEST;
  GRANT SELECT ANY SEQUENCE TO HOLON_TEST;
  GRANT UNLIMITED TABLESPACE TO HOLON_TEST;