# holon/oracle12

# hostname: localhost
# port: 1521
# sid: xe
# username: system
# password: oracle

FROM truevoly/oracle-12c

ADD init.sql /docker-entrypoint-initdb.d/

EXPOSE 1521
EXPOSE 8080
